# Generated by Django 6.0 on 2026-01-01 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_account_alter_expense_options_alter_income_options_and_more'),
        ('sales', '0003_sale_is_stock_out_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('Tsh', 'Tanzanian Shillings'), ('USD', 'US Dollars'), ('EUR', 'Euros')], default='Tsh', max_length=10),
        ),
        migrations.AddField(
            model_name='income',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='currency',
            field=models.CharField(choices=[('Tsh', 'Tanzanian Shillings'), ('USD', 'US Dollars'), ('EUR', 'Euros')], default='Tsh', max_length=10),
        ),
        migrations.AddField(
            model_name='income',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='income',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='income',
            name='sale',
            field=models.ForeignKey(blank=True, help_text='Linked sale if income is from sales', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('Tsh', 'Tanzanian Shillings'), ('USD', 'US Dollars'), ('EUR', 'Euros')], default='Tsh', max_length=10),
        ),
    ]
