# Generated by Django 6.0 on 2026-01-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_expense_currency_income_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='income',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Card', 'Credit Card'), ('Mobile', 'Mobile Money')], default='Bank', max_length=20),
        ),
    ]
