# Generated by Django 6.0 on 2026-01-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_income_is_paid_income_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='leave_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Leave Deductions'),
        ),
    ]
