# Generated by Django 6.0 on 2026-01-25 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_payroll_leave_deductions'),
        ('hr', '0004_leavetype_alter_employee_options_and_more'),
        ('procurement', '0002_alter_purchaseorder_options_and_more'),
        ('sales', '0004_alter_payment_options_alter_sale_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='payroll',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='leave_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='finance_exp_date_677539_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_type'], name='finance_exp_expense_f68925_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_paid'], name='finance_exp_is_paid_26be49_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['purchase_order'], name='finance_exp_purchas_4b5002_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['date'], name='finance_inc_date_8372c6_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['income_type'], name='finance_inc_income__906cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['is_active'], name='finance_inc_is_acti_6c00ad_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['sale'], name='finance_inc_sale_id_45c7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['employee'], name='finance_pay_employe_f3b560_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['month', 'year'], name='finance_pay_month_c00550_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['is_paid'], name='finance_pay_is_paid_408ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='finance_tra_transac_2a23c2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='finance_tra_date_f21d66_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['debit_account'], name='finance_tra_debit_a_3a439f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['credit_account'], name='finance_tra_credit__6ac4fd_idx'),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='accountingperiod',
            unique_together={('year', 'month')},
        ),
    ]
