# Generated by Django 6.0 on 2026-01-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_accountingperiod_alter_payroll_basic_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='currency',
            field=models.CharField(choices=[('Tsh', 'Tanzanian Shillings'), ('USD', 'US Dollars'), ('EUR', 'Euros')], default='Tsh', max_length=10),
        ),
    ]
