# Generated by Django 6.0 on 2026-03-02 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_payroll_currency'),
        ('hr', '0004_leavetype_alter_employee_options_and_more'),
        ('procurement', '0002_alter_purchaseorder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Payroll', 'Payroll')], max_length=20)),
                ('object_id', models.IntegerField()),
                ('requested_changes', models.JSONField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('Inventory', 'Inventory'), ('Sales', 'Sales'), ('HR', 'HR'), ('Procurement', 'Procurement'), ('Finance', 'Finance')], max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_role', models.CharField(default='Admin', max_length=50)),
            ],
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['payment_date'], name='finance_exp_payment_c18045_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['payment_date'], name='finance_pay_payment_87a5b9_idx'),
        ),
        migrations.AddField(
            model_name='financeeditrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_finance_edits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financeeditrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_edit_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
