# Generated by Django 6.0 on 2026-04-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_financeeditrequest_systemnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeeditrequest',
            name='edit_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
