# Generated by Django 6.0 on 2025-12-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('', '--- Select Department ---'), ('HR', 'Human Resources'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Procurement', 'Procurement'), ('Inventory', 'Inventory/Warehouse'), ('Safety', 'Safety & Compliance'), ('IT', 'Information Technology'), ('Operations', 'Operations'), ('Sales', 'Sales'), ('Administration', 'Administration')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('', '--- Select Position ---'), ('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('Staff', 'Staff'), ('Officer', 'Officer'), ('Assistant', 'Assistant'), ('Director', 'Director'), ('Coordinator', 'Coordinator')], max_length=50),
        ),
    ]
