# Generated by Django 6.0 on 2025-12-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockin',
            old_name='source',
            new_name='supplier',
        ),
    ]
