# Generated by Django 6.0 on 2025-12-28 21:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_source_stockin_supplier'),
        ('procurement', '0002_alter_purchaseorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.AlterModelOptions(
            name='stockin',
            options={'ordering': ['-date'], 'verbose_name': 'Stock In', 'verbose_name_plural': 'Stock Ins'},
        ),
        migrations.AlterModelOptions(
            name='stockout',
            options={'ordering': ['-date'], 'verbose_name': 'Stock Out', 'verbose_name_plural': 'Stock Outs'},
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='last_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='minimum_stock',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='item',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average unit cost', max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_of_measure',
            field=models.CharField(default='pcs', help_text='e.g., pcs, kg, liter, box', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stockin',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockin',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_entries', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='received_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockin',
            name='reference',
            field=models.CharField(blank=True, help_text='PO Number, GRN, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockin',
            name='source',
            field=models.CharField(choices=[('Purchase', 'Purchase Order'), ('Return', 'Customer Return'), ('Production', 'Production'), ('Adjustment', 'Stock Adjustment'), ('Other', 'Other')], default='Purchase', max_length=20),
        ),
        migrations.AddField(
            model_name='stockin',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockin',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockout',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stockout',
            name='issued_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockout',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockout',
            name='purpose',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Production', 'Production Use'), ('Damage', 'Damaged/Lost'), ('Sample', 'Sample/Testing'), ('Internal', 'Internal Use'), ('Other', 'Other')], default='Internal', max_length=20),
        ),
        migrations.AddField(
            model_name='stockout',
            name='reference',
            field=models.CharField(blank=True, help_text='Sales Order, Requisition, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockout',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockout',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Raw Material', 'Raw Material'), ('Finished Goods', 'Finished Goods'), ('Consumables', 'Consumables'), ('Tools & Equipment', 'Tools & Equipment'), ('Office Supplies', 'Office Supplies'), ('Other', 'Other')], default='Raw Material', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ins', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_outs', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
