# Generated by Django 6.0 on 2025-12-31 00:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockin_created_at_stockout_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='last_purchase_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='department',
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='unit_cost',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('RAW_MATERIALS', 'Raw Materials'), ('CHEMICALS', 'Chemicals'), ('OTHERS', 'Others')], default='RAW_MATERIALS', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=3, default=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='reorder_level',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='issued_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='purpose',
            field=models.CharField(choices=[('SALE', 'Sale'), ('DAMAGE', 'Damage'), ('INTERNAL_USE', 'Internal Use'), ('OTHER', 'Other')], default='INTERNAL_USE', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('STOCK_IN', 'Stock In'), ('STOCK_OUT', 'Stock Out'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('previous_quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('new_quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='inventory.item')),
            ],
            options={
                'verbose_name': 'Stock History',
                'verbose_name_plural': 'Stock Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
