# Generated by Django 6.0 on 2025-12-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_item_last_purchase_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockin',
            name='purchase_order',
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_of_measure',
            field=models.CharField(default='kg', help_text='e.g., kg, pcs, liter, box', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name',), name='unique_item_name'),
        ),
    ]
