# Generated by Django 6.0 on 2025-12-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_stockin_purchase_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('RAW_MATERIALS', 'Raw Materials'), ('CHEMICALS', 'Chemicals'), ('FINISHED_GOODS', 'Finished Goods'), ('OTHERS', 'Others')], default='RAW_MATERIALS', max_length=50),
        ),
    ]
