# Generated by Django 6.0 on 2025-12-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stockhistory_reference_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockout',
            name='sale_reference',
            field=models.CharField(blank=True, help_text='Sale number if purpose is SALE', max_length=100, null=True),
        ),
    ]
