# Generated by Django 6.0 on 2025-12-31 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_stockout_sale_reference'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost price in Tsh', max_digits=12),
        ),
        migrations.AddField(
            model_name='item',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Selling price in Tsh', max_digits=12),
        ),
        migrations.AddField(
            model_name='stockout',
            name='linked_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_outs', to='sales.sale'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='purpose',
            field=models.CharField(choices=[('SALE', 'Sale'), ('TRANSFER', 'Transfer to Another Location'), ('INTERNAL_USE', 'Internal Use'), ('DAMAGE', 'Damage / Loss'), ('SAMPLE', 'Sample / Testing'), ('RETURN', 'Return to Supplier'), ('OTHER', 'Other')], default='INTERNAL_USE', max_length=20),
        ),
    ]
