# Generated by Django 6.0 on 2026-01-03 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_item_purchase_price_item_selling_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_history', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ins', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_outs', to='inventory.item'),
        ),
    ]
