# Generated by Django 6.0 on 2026-02-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_stockin_status_alter_stockout_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockin',
            options={},
        ),
    ]
