# Generated by Django 6.0 on 2026-03-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_stockin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockin',
            options={'ordering': ['-date'], 'verbose_name': 'Stock In', 'verbose_name_plural': 'Stock Ins'},
        ),
    ]
