# Generated by Django 6.0 on 2026-01-27 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('EXPORT', 'Export'), ('ACCESS_DENIED', 'Access Denied')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('SALES', 'Sales'), ('FINANCE', 'Finance'), ('INVENTORY', 'Inventory'), ('HR', 'HR'), ('PROCUREMENT', 'Procurement'), ('MARKETING', 'Marketing'), ('SAFETY', 'Safety'), ('DASHBOARD', 'Dashboard'), ('AUTH', 'Authentication'), ('OTHER', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
