# Generated by Django 6.0 on 2026-04-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_action_alter_auditlog_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('SALES', 'Sales'), ('FINANCE', 'Finance'), ('INVENTORY', 'Inventory'), ('HR', 'HR'), ('PROCUREMENT', 'Procurement'), ('MARKETING', 'Marketing'), ('SAFETY', 'Safety'), ('DASHBOARD', 'Dashboard'), ('AUTH', 'Authentication'), ('AUDIT', 'Audit'), ('OTHER', 'Other')], db_index=True, max_length=50),
        ),
    ]
