# Generated by Django 6.0 on 2025-12-31 15:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_item_purchase_price_item_selling_price_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='stock_out',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='inventory_item',
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='Tsh', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='currency',
            field=models.CharField(choices=[('Tsh', 'Tanzanian Shillings'), ('USD', 'US Dollars'), ('EUR', 'Euros')], default='Tsh', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Exchange rate to Tsh (1 foreign currency = X Tsh)', max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='inventory_stock_out',
            field=models.OneToOneField(blank=True, help_text='Linked inventory stock out record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_relation', to='inventory.stockout'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='currency',
            field=models.CharField(default='Tsh', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount in Tsh', max_digits=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in Tsh', max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount in Tsh', max_digits=15),
        ),
        migrations.AlterField(
            model_name='sale',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount in Tsh', max_digits=15),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount in Tsh', max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount in Tsh', max_digits=15),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount in Tsh', max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount in Tsh', max_digits=15),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount in Tsh', max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax rate in percentage (e.g., 18 for 18%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount in Tsh', max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price in Tsh per unit', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount in Tsh', max_digits=12),
        ),
    ]
