# Generated by Django 6.0 on 2025-12-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_item_purchase_price_item_selling_price_and_more'),
        ('sales', '0002_remove_sale_stock_out_remove_saleitem_inventory_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_stock_out_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='stock_out_processed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='stock_out_request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='is_stocked_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='stock_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('STOCK_OUT_PENDING', 'Stock Out Pending')], default='DRAFT', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='saleitem',
            unique_together={('sale', 'item')},
        ),
    ]
