# Generated by Django 6.0 on 2026-01-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_is_stock_out_requested_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date']},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='saleitem',
            unique_together=set(),
        ),
    ]
